;; ============================================================
;;  _PEB_LAYERS_generated.lsp  —  AUTO-GENERATED. DO NOT EDIT.
;;  Single source: Rule_Book/PEB_LAYERS.csv  (build_engine_standard.py)
;;  Row shape: (name  ACI-colour  linetype  lineweight-mm)
;; ============================================================
(setq *PEB-LAYERS*
  '(
    ("BORDER"              7    "Continuous" 0.50)
    ("TITLEBLOCK"          1    "Continuous" 0.35)
    ("TB-HEADER"           1    "Continuous" 0.50)
    ("GRID"                150  "Continuous" 0.35)
    ("GRID-LINES"          8    "CENTER" 0.09)
    ("GRID-TEXT"           1    "Continuous" 0.09)
    ("COLUMN-HATCH"        8    "Continuous" 0.09)
    ("STRUCTURE"           7    "Continuous" 0.25)
    ("COLUMNS"             1    "Continuous" 0.50)
    ("COL-CENTER"          1    "CENTER" 0.09)
    ("CL"                  1    "CENTER" 0.09)
    ("CROSS"               4    "Continuous" 0.18)
    ("BOLTS"               7    "Continuous" 0.09)
    ("PLATES"              1    "Continuous" 0.35)
    ("FRAME"               1    "Continuous" 0.30)
    ("FRAME-FILL"          8    "Continuous" 0.09)
    ("RIDGE"               5    "HIDDEN" 0.18)
    ("RAFTER"              8    "HIDDEN" 0.09)
    ("PURLINS"             6    "Continuous" 0.13)
    ("GIRTS"               6    "Continuous" 0.13)
    ("SHEETING"            4    "Continuous" 0.09)
    ("SKY LIGHT"           151  "Continuous" 0.50)
    ("WALL LIGHT"          151  "Continuous" 0.50)
    ("LOUVER"              3    "Continuous" 0.50)
    ("RIDGE-VENT"          4    "Continuous" 0.50)
    ("CLADDING"            5    "Continuous" 0.18)
    ("COL-OUTER"           4    "DASHDOT" 0.09)
    ("GUTTER"              4    "Continuous" 0.18)
    ("DIMENSIONS"          6    "Continuous" 0.13)
    ("ARROWS"              3    "Continuous" 0.13)
    ("FALL"                1    "Continuous" 0.35)
    ("TEXT"                7    "Continuous" 0.13)
    ("AREA-MARK"           8    "Continuous" 0.18)
    ("OPEN"                6    "Continuous" 0.18)
    ("BRICK-WALL"          30   "Continuous" 0.25)
    ("RCC-COLUMN"          8    "Continuous" 0.35)
    ("GROUND"              7    "Continuous" 0.50)
    ("GROUND-HATCH"        8    "Continuous" 0.09)
    ("HATCHR"              32   "Continuous" 0.30)
    ("HATCH"               8    "Continuous" 0.05)
    ("COMP-MEZZ-BEAM"      5    "Continuous" 0.40)
    ("COMP-MEZZ-JOIST"     3    "Continuous" 0.30)
    ("COMP-MEZZ-JOIST-SEC" 4    "Continuous" 0.18)
    ("SLIDING DOOR"        42   "Continuous" 0.50)
    ("SLIDING DOOR-FACE"   252  "Continuous" 0.05)
    ("SLIDING DOOR-HW"     9    "Continuous" 0.18)
   ))
(princ)
