;; AUTO-GENERATED by compile_rulebook.py from the Rule Book — DO NOT hand-edit.
;; Every number measured straight from MAIMAAR_RULE_BOOK.dxf. Change the drawing, re-run the compiler.
;; Read in the engine with:  (cdr (assoc "brace_reach_xD" *PEB-RULES*))
(setq *PEB-RULES* (list
  (cons "col_depth_div" 27)
  (cons "flange_width_xD" 0.4)
  (cons "flange_thick_xD" 0.04)
  (cons "web_thick_xD" 0.026)
  (cons "bolt_dia_xD" 0.077)
  (cons "bolt_x_xD" 0.105)
  (cons "bolt_y_xD" 0.18)
  (cons "endwall_depth_x_main" 0.5)
  (cons "rcc_square_mm" 520.0)
  (cons "bubble_radius_mm" 620.0)
  (cons "fall_width_mm" 600.0)
  (cons "brace_reach_xD" 0.456)
  (cons "brace_web_offset_xD" 0.013)))
(princ)
